### ISSUE TITLE
Just for ESX?

### ISSUE THREAD

**Issue by mxhdg** [EgoPvP/sitdown#2]
A question, not really an issue, based on this being a refactor of the original ESX script, is it safe to guess this is still just for ESX, and will not work out of the box with VRP?

**Comment by NoobKeksTV** [comment]
in its current state yeah. But you could redo some stuff and make it standalone. maybe ill do a version of that 2

**Comment by mxhdg** [comment]
I've never written anything for fivem, I may fork it, and make it a personal project.
