### ISSUE TITLE
Can't get up from the chair 

### ISSUE THREAD

**Issue by twitoorel1** [EgoPvP/sitdown#3]
The script works on me sitting in a chair but I can not get up, is there any particular button to get up?
The F button does not work to get up it just returns to the seat.

**Comment by Brutuss** [comment]
Use X

**Comment by NoobKeksTV** [comment]
Without any proper steps, logs & info we sadly can not support you.
As this issue is very old i will close it. Please open it again or create a new one if the issue persists
