### ISSUE TITLE
Some error from esx 1.2?

### ISSUE THREAD

**Issue by nicxes** [EgoPvP/sitdown#4]
Im having this issue with my current esx 1.2, any idea how to fix it?

![image](https://user-images.githubusercontent.com/8798356/120914713-4c17c980-c676-11eb-9801-174fe6b305e0.png)

**Comment by illusdidi** [comment]
same error

**Comment by NoobKeksTV** [comment]
i think it has to do with the function how esx 1.1 & 1.2 return entitys in their methods i used, cant confirm this problem tho.

Tested all versions from 1.0 to final legacy, got no problems

**Comment by DubStepMad** [comment]
I get the same error, fresh Legacy server as well.

**Comment by NoobKeksTV** [comment]
like stated in the scripts dependencies, you need a ESX version prior to 1.1 final. 
See https://github.com/EgoPvP/sitdown#dependencies


As this is an old issue, i will close this. for any other issues, please open it again or open a new one.
